OLED_DRIVER_ENABLE = yes
ENCODER_ENABLE = no
RGBLIGHT_ENABLE = yes

TAP_DANCE_ENABLE = no
STENO_ENABLE = no
TERMINAL_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
KEY_LOCK_ENABLE = no
VELOCIKEY_ENABLE = no
WPM_ENABLE = yes

LEADER_ENABLE = no
COMBO_ENABLE = no
